include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
linter:
  rules:
    require_trailing_commas: true
    prefer_single_quotes: true
    sort_pub_dependencies: true

